version: "3"

services:
  php:
    build: ./${BUILD_PATH}
    container_name: ${CONTAINER_NAME}
    ports:
      - 8080:80
    volumes:
      - .${REPOSITORY_PATH}:/var/www/html
      - vendor-store:/var/www/html/vendor
    networks:
      - my_laravel_network
      - my_infra_network

volumes:
  vendor-store:

networks:
  my_laravel_network:
    name: my_laravel_network
  my_infra_network:
    external: true
    name: my_infra_network
